# === Site Settings ===
title: Mandre's Blog
tagline: Reflections, Books, and Beyond
description: >-
  A personal blog and portfolio where I share book reviews, side projects, and thoughts outside of work.

url: "https://ismandre.github.io"   # your GitHub Pages URL
baseurl: ""                         # empty if hosted at the root (e.g., username.github.io)

lang: en
timezone: Europe/Zagreb

theme: jekyll-theme-chirpy

# === Author Settings ===
author:
  name: Mandre
  bio: >
    Software engineer by day, bookworm and side project explorer by night.
  email: your@email.com

social:
  name: Mandre
  links:
    - https://github.com/ismandre
    - https://www.linkedin.com/in/yourprofile/
    - mailto:your@email.com
    
# === Avatar ===
avatar: /assets/img/avatar.gif

# === Plugins ===
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# === Analytics ===
google_analytics:
  id: "" # e.g., G-XXXXXXXXXX

# === SEO & Sitemap ===
tagline_separator: "|"
title_separator: "-"
google_site_verification: ""
bing_site_verification: ""

# === Pagination ===
paginate: 5
paginate_path: /page:num/

# === Markdown Options ===
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# === Build Settings ===
permalink: /:year/:month/:day/:title/
exclude:
  - .github/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# === Defaults for Posts ===
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true

# === Comments (Optional) ===
# To enable, set your provider and credentials
comments:
  provider: false  # options: giscus | disqus | utterances | false

# === Footer ===
footer:
  since: 2025
  license:
    type: MIT
    url: https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/LICENSE

